### ISSUE TITLE
Add a settings link to the list of plugin action links

### ISSUE THREAD

**Issue by frankiejarrett** [xwp/wp-dependency-minification#13]
Sometimes it can be confusing for users to be able to find the settings screen for a plugin if they don't know what menu it's under. In this case, Dependency Minification is located under the **Tools** menu, which can be a commonly overlooked menu as most plugins place their links under the **Settings** menu parent.

Adding a **Settings** link to the plugin action link list can help users find the admin page quickly immediately after activating the plugin for the first time.

![settings-link](https://f.cloud.github.com/assets/522158/942226/0ceef7a6-0194-11e3-9a60-499faf77e292.png)

**Comment by frankiejarrett** [comment]
PR issued https://github.com/x-team/wp-dependency-minification/pull/15

**Comment by westonruter** [comment]
@fjarrett thanks for this!

Tip, to attach the pull request to an existing issue, you can do:

``` bash
hub pull-request -i 13 -b develop
```

**Comment by westonruter** [comment]
Cheers! Merged #15.
