### ISSUE TITLE
Support HTML5 defer, async script tag attributes

### ISSUE THREAD

**Issue by lkraav** [xwp/wp-dependency-minification#20]
While WordPress core support has stalled on this http://core.trac.wordpress.org/ticket/12009 perhaps something custom can be figured out for this plugin to hold us over?

**Comment by westonruter** [comment]
Great suggestion! But I think the best thing to do in this case is to create a script loader which loads the desired script asynchronously. This way the script loader can be concatenated with all the other scripts, but the target script still loads asynchronously.

I've used [`loadScript`](http://www.nczonline.net/blog/2009/07/28/the-best-way-to-load-external-javascript/) by @nzakas for this in the past. So the enqueued script (e.g. `async-script-loader.js`) could consist merely of:

``` js
loadScript( 'http://example.com/async-script.js' );
```

Does that work?

**Comment by lkraav** [comment]
Isn't http://headjs.com exactly this?

**Comment by westonruter** [comment]
I guess, except loadScript only does one thing.

**Comment by lkraav** [comment]
Hmmm, I think google pagespeed also has an example implementation https://developers.google.com/speed/docs/insights/BlockingJS#deferJS

So who can make an authoritative decision on what is the best course to take?

**Comment by westonruter** [comment]
It is up to each site developer to decide which scripts should be async and
the method for how they should be loaded.

**Comment by lkraav** [comment]
OK, maybe it becomes a documentation bug. I'm sure a load of people that didn't know about this before (<-- recently me), could benefit if the plugin pointed to these valuable resources or had an on/off checkbox/filter.

**Comment by westonruter** [comment]
I think this would be better as an independent plugin, as it can be a standalone feature. Pretty useful actually. So this “Async Scripts” plugin could have an `async_script` filter which returns a boolean `false` by default. A theme or plugin could then opt-in to making a script async by filtering it to be `true`, and then swap out the original script with a wrapper that makes it asynchronous.

For example consider a plugin that does:

``` php
wp_enqueue_script( 'foo', 'http://example.com/foo.js' );
```

The theme or plugin could do this:

``` php
add_filter( 'async_script', function ( $is_async, $handle, $src ) {
    if ( 'foo' === $handle ) {
        $is_async = true;
    }
    return $is_async;
}, 10, 3 );
```

And then the script enqueued with the `foo` handle could be replaced with another script pointing to: `/wp-admin/admin-ajax.php?action=async_script&src=http://example.com/foo.js` which would then wrap the original src in a `loadScript` call:

``` js
loadScript( 'http://example.com/foo.js' );
```

And this wrapper could then get concatenated with the other scripts.
