### ISSUE TITLE
Document some reasons why some JS and CSS might not get automatically minified

### ISSUE THREAD

**Issue by lkraav** [xwp/wp-dependency-minification#22]
I'm seeing this happen on some WPML plugin resources. Resources consistently stay out of minification process. Maybe it's a filter priority issue?

```
wp-content/plugins/sitepress-multilingual-cms/res/js/sitepress.js
wp-content/plugins/sitepress-multilingual-cms/res/css/language-selector.css?v=2.9
```

I'm going to investigate what's special about them.

**Comment by westonruter** [comment]
This is probably related to #9.

**Comment by westonruter** [comment]
@lkraav just released 0.9.3 which includes PR #24 and fixes #9. If you update, do you still see these WPML plugins getting excluded from minification?

/cc @shadyvb

**Comment by shadyvb** [comment]
@Ikrav I happen to be a happy customer of WPML products, and i just checked the code to find out that they do not use WP API to register/enqueue scripts, they just echo the HTML manually, not sure why though!

So it won't work unless the plugin developers switch to WP API for their resources registration. Feel free to notify them about it.

**Comment by westonruter** [comment]
Ooooh, shame on WPML! :frowning:
