### ISSUE TITLE
wp_localize_script variable lost in minification

### ISSUE THREAD

**Issue by lkraav** [xwp/wp-dependency-minification#28]
I'm seeing a variable getting lost (no "/\* wp_localize_script($data_handle): */\n" visible in the source, while some others are) and it's killing the whole page's JS.

Investigating further. Opening the issue for some possible early feedback from core devs if this should even be possible, so I'm not chasing ghosts.

**Comment by lkraav** [comment]
At first sight, I'm seeing:
- $dep = $wp_deps->registered[$new_handle]; has two _WP_Dependency objects with the same "handle" property, but different "extra" property, to work with
- $dep->add_data( $key, $data ); apparently will end up adding only the last come last serve dependecy extra info, overwriting any earlier "extra"-s

**Comment by lkraav** [comment]
Yes I'm convinced now handle extra data processing is broken when two scripts from a single group include extra data. Only the last one is added by wpdm. Seeing if I can patch this.

**Comment by westonruter** [comment]
I believe this is the same issue which was reported at http://wordpress.org/support/topic/jqueryjs-generated-css-error

**Comment by westonruter** [comment]
Released as version 0.9.5: 
http://wordpress.org/plugins/dependency-minification/
https://github.com/x-team/wp-dependency-minification/releases/tag/0.9.5
