### ISSUE TITLE
Extract the admin functions from the main class

### ISSUE THREAD

**Issue by nash-ye** [xwp/wp-dependency-minification#31]
I really like this plugin, and I want to make it better :)

The idea of this ticket is to make this plugin more easier to develop and more elegant to read. so we want to separate the plugin main class file to some small files loaded only when needed.

The first step is to separate the plugin admin functions to another file .. 
let's start hacking !

**Comment by westonruter** [comment]
As chatted over hangouts, you're going to base your refactoring in a new feature branch first merging the currently-open pull requests #27 and #29 so that merging later will be less of a bear.

**Comment by nash-ye** [comment]
Ok.. @westonruter can you assign this issue to me.. I have done it and I will update the fork tomorrow.

**Comment by westonruter** [comment]
@nash-ye I can't assign the ticket to you because you don't have push access (yet). So just put the commits together into a feature branch on your fork, and open a pull request into the `develop` branch, and mention this issue #31 in the pull request description.

**Comment by nash-ye** [comment]
@westonruter Ok :), I had finished 90% percent of this, you can see it in my fork:
https://github.com/nash-ye/wp-dependency-minification/tree/temp

I have also resolve some other bugs, I will publish about them today.
Everything should work fine now, you can test it.

**Comment by westonruter** [comment]
It does make it harder to code review when the pull request has many changes. Ideally each PR would tackle one thing.

**Comment by nash-ye** [comment]
@westonruter Yeah, I hate this too but it's normal for this type of issues :)
