### ISSUE TITLE
Show minification request date/time in admin page

### ISSUE THREAD

**Issue by shadyvb** [xwp/wp-dependency-minification#43]
Sometimes the request is not carried out successfully, be it for a faulty URL, or a security barrier or anything else.

We need to show date/time of requests, and accordingly warn the user of such delays, and probably give him a way to instantly generate those minifed groups ?

**Comment by westonruter** [comment]
Good idea. Yeah, there could be a button to force-trigger the action that normally would be triggered by wp-cron.

How would we report if a request was carried out successfully or not? How could we detect for such errors if cron can't be pinged in the first place.

**Comment by shadyvb** [comment]
@westonruter Reporting a job that has a request time of X while X >= cron interval or something. 

And on the force-trigger call we can make a non-async AJAX so we get the result instantly.

**Comment by westonruter** [comment]
I don't think we have to go the route of doing a synchronous XHR. As long as the request is done in-page and not in background via cron, I think we're good.

**Comment by shadyvb** [comment]
That's actually what i meant, i didn't mean `asyc: false` ( although it pretty much seems so! ).
